/// Fact table containing invoiced sales transactions including revenue, profit, tax and quantity.
table InvoicedSales
	lineageTag: cbf6970b-216d-4d0a-8614-1a7bc9fd2ad3
	sourceLineageTag: [Gold].[InvoicedSales]

	/// Sum of extended price across all invoiced sales
	measure 'Total Revenue' = SUM(InvoicedSales[ExtendedPrice])
		formatString: $#,##0.00

	/// Sum of gross profit across all invoiced sales
	measure 'Total Gross Profit' = SUM(InvoicedSales[GrossProfit])
		formatString: $#,##0.00

	/// Sum of tax amount across all invoiced sales
	measure 'Total Tax' = SUM(InvoicedSales[TaxAmount])
		formatString: $#,##0.00

	/// Sum of quantity across all invoiced sales
	measure 'Total Quantity Invoiced' = SUM(InvoicedSales[Quantity])
		formatString: #,##0

	/// Count of distinct invoices
	measure 'Invoice Count' = DISTINCTCOUNT(InvoicedSales[InvoiceID])
		formatString: #,##0

	/// Gross profit as a percentage of revenue
	measure 'Gross Profit Margin %' = DIVIDE([Total Gross Profit], [Total Revenue], 0)
		formatString: 0.00%

	/// Average revenue per distinct invoice
	measure 'Average Revenue per Invoice' = DIVIDE([Total Revenue], [Invoice Count], 0)
		formatString: $#,##0.00

	/// Hidden; primary key for the invoice, used as relationship key
	column InvoiceID
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: ddc34db3-ce11-4bd6-a928-451014871d5b
		sourceLineageTag: InvoiceID
		summarizeBy: none
		sourceColumn: InvoiceID

		annotation SummarizationSetBy = Automatic

	/// Hidden; primary key for the invoice line, used as relationship key
	column InvoiceLineID
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 3e97ce9d-918e-4fce-9a8b-ba935721f4f4
		sourceLineageTag: InvoiceLineID
		summarizeBy: none
		sourceColumn: InvoiceLineID

		annotation SummarizationSetBy = Automatic

	/// Hidden; foreign key to Customer table, used as relationship key
	column CustomerID
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 253797bf-15fe-4329-9fe7-08db83f27c2c
		sourceLineageTag: CustomerID
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	/// Hidden; foreign key to Products table, used as relationship key
	column StockItemID
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 5f13f874-3c3a-42f7-a6a0-54521e553734
		sourceLineageTag: StockItemID
		summarizeBy: none
		sourceColumn: StockItemID

		annotation SummarizationSetBy = Automatic

	/// Hidden; foreign key to Salesperson table, used as relationship key
	column SalespersonPersonID
		dataType: int64
		isHidden
		formatString: 0
		sourceProviderType: int
		lineageTag: 4d7b2119-445e-40a0-8c98-6f6fbb3e3ba7
		sourceLineageTag: SalespersonPersonID
		summarizeBy: none
		sourceColumn: SalespersonPersonID

		annotation SummarizationSetBy = Automatic

	/// Date the invoice was issued
	column InvoiceDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: ae645d7a-65bf-4a3f-a57b-4d38538cfb0c
		sourceLineageTag: InvoiceDate
		summarizeBy: none
		sourceColumn: InvoiceDate

		annotation SummarizationSetBy = Automatic

	/// Timestamp of the last update to this record
	column LastUpdated
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 624d5e67-b811-481b-a356-7a77e052c573
		sourceLineageTag: LastUpdated
		summarizeBy: none
		sourceColumn: LastUpdated

		annotation SummarizationSetBy = Automatic

	/// Number of units sold on this invoice line
	column Quantity
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: dc2359eb-7609-4b05-af6f-380de912af31
		sourceLineageTag: Quantity
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	/// Total price for this invoice line (unit price × quantity)
	column ExtendedPrice
		dataType: double
		sourceProviderType: decimal(18, 2)
		lineageTag: 8a453e63-bcb8-4a74-9431-80cb79480bd9
		sourceLineageTag: ExtendedPrice
		summarizeBy: sum
		sourceColumn: ExtendedPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Gross profit for this invoice line (revenue minus cost)
	column GrossProfit
		dataType: double
		sourceProviderType: decimal(18, 2)
		lineageTag: d264ce80-49ff-429f-9ec2-f27e80038913
		sourceLineageTag: GrossProfit
		summarizeBy: sum
		sourceColumn: GrossProfit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Tax amount charged on this invoice line
	column TaxAmount
		dataType: double
		sourceProviderType: decimal(18, 2)
		lineageTag: 603f865f-0f56-4a4c-a0ec-79da6f51ab19
		sourceLineageTag: TaxAmount
		summarizeBy: sum
		sourceColumn: TaxAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition InvoicedSales = entity
		mode: directLake
		source
			entityName: InvoicedSales
			schemaName: Gold
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

